language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_DEPRECATIONS_HELPER: weak

cache:
  directories:
    - .composer/cache

before_install:
  - alias composer=composer\ -n && composer self-update

install:
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - php bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - composer require satooshi/php-coveralls
 - php bin/coveralls

notifications:
  email:
    - developer@ynloultratech.com