api:
    resource: .
    type:     restful
    prefix:   /{version}
    defaults: {"_format":"json"}

api_doc:
      resource: '@RestfulPlatformBundle/Resources/config/routing/doc.yml'
      prefix:   /{version}/doc